platform :ios, '13.0'
# Use CDN as primary source
source 'https://cdn.cocoapods.org/'


target 'AelfApp' do
  use_frameworks!
  inhibit_all_warnings!
  
  # Network
  pod 'Moya', '~> 15.0' # 网络请求 https://github.com/Moya/Moya
  pod 'Moya/RxSwift', '~> 15.0'
  
  # Image
  pod 'Kingfisher', '~> 7.0' # 图片下载 https://github.com/onevcat/Kingfisher
  
  # Layout
  pod 'SnapKit', '~> 5.0' # Layout 布局 https://github.com/SnapKit/SnapKit
  
  # Database
  pod 'WCDB.swift', '~> 2.0' # 腾讯数据库 https://github.com/Tencent/wcdb
  
  # Keyboard
  pod 'IQKeyboardManagerSwift' # 键盘管理 https://github.com/hackiftekhar/IQKeyboardManager
  
  # Crash Analytics
  pod 'Bugly' # 崩溃统计 https://bugly.qq.com/v2/

  # UI Components
  pod 'LTMorphingLabel' # 文字动画 https://github.com/lexrus/LTMorphingLabel
  pod 'Schedule' # 时间调度 https://github.com/luoxiu/Schedule
  pod 'ViewAnimator' # 动画库 https://github.com/marcosgriselli/ViewAnimator
  pod 'SwifterSwift', '~> 6.0' # 类似 YYKit https://github.com/SwifterSwift/SwifterSwift
  pod 'Localize-Swift' # 国际化 https://github.com/marmelroy/Localize-Swift
  pod 'Then' # 语法糖 https://github.com/devxoul/Then
  pod 'SwiftMessages' #  UI 弹框库 https://github.com/SwiftKickMobile/SwiftMessages
  pod 'DZNEmptyDataSet'  # 老版空态框架 https://github.com/dzenbot/DZNEmptyDataSet
  pod 'KafkaRefresh' # 刷新框架 https://github.com/OpenFeyn/KafkaRefresh

  pod 'SVProgressHUD' # HUD 弹框
  pod 'Hero'  # https://github.com/HeroTransitions/Hero
  pod 'MYTableViewIndex' # 地址薄索引
  pod 'MarqueeLabel' # 跑马灯 https://github.com/cbpowell/MarqueeLabel
  pod 'FSPagerView' # 轮播图 https://github.com/WenchaoD/FSPagerView
  pod 'JXSegmentedView' # Segment 分页 https://github.com/pujiaxin33/JXSegmentedView
  pod 'SwiftyAttributes' # 富文本字符串 https://github.com/eddiekaiger/SwiftyAttributes
  pod 'UITextView+Placeholder'
  pod 'CropViewController' # Crop Image https://github.com/TimOliver/TOCropViewController
  pod 'ESTabBarController-swift' # https://github.com/eggswift/ESTabBarController
  pod 'WKWebViewJavascriptBridge', '~> 1.2.0' # https://github.com/Lision/WKWebViewJavascriptBridge
  pod 'FoldingCell'  # 折叠 cell https://github.com/Ramotion/folding-cell

  pod 'Closures' # 事件回调 https://github.com/vhesener/Closures

  # Rx 相关
  pod 'RxSwift', '~> 6.0' # https://github.com/ReactiveX/RxSwift
  pod 'RxCocoa', '~> 6.0'
  pod 'RxDataSources', '~> 5.0'  # https://github.com/RxSwiftCommunity/RxDataSources
  pod 'NSObject+Rx', '~> 5.0' # https://github.com/RxSwiftCommunity/NSObject-Rx
  
  # ObjectMapper for JSON parsing (use ObjectMapper directly instead of Moya-ObjectMapper)
  pod 'ObjectMapper', '~> 4.0'
  
  # Form validation - Using local implementation (external Validator lib unavailable)
  # See Aelf/AelfApp/Classes/Utility/Validate/Validator.swift

  # Cache
  pod 'Cache' # 缓存库

  # 区块链相关库
  # HdWalletKit.swift - 轻量级 BIP39/BIP32/BIP44 实现 (from UnstoppableWallet team)
  # https://github.com/horizontalsystems/hd-wallet-kit-ios
  pod 'HdWalletKit.swift', '~> 1.5'
  
  pod 'KeychainSwift' # https://github.com/evgenyneu/keychain-swift
  pod 'SwiftyRSA' # https://github.com/TakeScoop/SwiftyRSA
  pod 'CryptoSwift', '~> 1.8' # For cryptographic functions

  # Umeng 推送 - Updated versions
  pod 'UMCommon'
  pod 'UMDevice'
  pod 'UMPush'
  
  pod 'JJException'  # Crash 拦截 https://github.com/jezzmemo/JJException
  
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['LD_NO_PIE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
      # Exclude arm64 for simulator to support M1 Macs with older pods
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64' if config.name == 'Debug'
    end
  end
  
  # Fix for Xcode 14+ signing issues
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
  end
end
